config:
  RC:
    url: "https://demoqa.com/"
    databaseUser: "user123"
    databasePassword: "pass123"
    browserName: "FIREFOX"
    envName: "RC"
    fullName: "Damian"
    email: "damian@rc.com"
    currentAddress: "address 1/21"
    permanentAddress: "address 21/21"
    wrongPasswordError: "Passwords must have at least one non alphanumeric character, one digit ('0'-'9'), one uppercase ('A'-'Z'), one lowercase ('a'-'z'), one special character and Password must be eight characters or longer."
  TC:
    url: "https://demoqa.com/"
    databaseUser: "user12345"
    databasePassword: "pass12345"
    browserName: "CHROME"
    envName: "TC"
    fullName: "Damian"
    email: "damian@tc.com"
    currentAddress: "address 1/21"
    permanentAddress: "address 21/21"
    wrongPasswordError: "Passwords must have at least one non alphanumeric character, one digit ('0'-'9'), one uppercase ('A'-'Z'), one lowercase ('a'-'z'), one special character and Password must be eight characters or longer."

activeEnvironment: "TC"